"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import django_on_heroku
import os
import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w(cnmqk4^qvw=j2(*3bss-@+g#i9@##^2_4hjc9wx(*+ng6rta'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['afternoon-brook-19806.herokuapp.com',
                 '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'product',
    'cart',
    'account',
    'orders',
    'crispy_forms',
    # 'django-anymail',
]
CRISPY_TEMPLATE_PACK = 'bootstrap5'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # BUG
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'product.context_processors.categories',
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [BASE_DIR / 'templates/static']
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"  # BUG
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


CART_SESSION_ID = 'cart'


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field
AUTH_USER_MODEL = 'account.UserBase'
LOGIN_REDIRECT_URL = '/account/dashboard'
LOGIN_URL = '/account/login/'

# email

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# mailgun necessário utilizar isso cada aplicação
#EMAIL_BACKEND = "anymail.backends.mailgun.EmailBackend"
#DEFAULT_FROM_EMAIL = "no-reply@meusite.com"
#SERVER_EMAIL = DEFAULT_FROM_EMAIL
# ANYMAIL = {
#  "MAILGUN_API_KEY": "b5e6cdcca872efe1861c27d1237b0feb-38029a9d-ddfc589b",
#  "MAILGUN_SENDER_DOMAIN": "",
# }
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# STRIPE  PAYMENT
# secret ley sk_test_51KfjEeLMpUX2gb0IKQxL8MPch3xZZEvZl0U1HiBGSsJnwT8oaQt9DIBjeQzaFaz0cY7Okv55U25VMRmqLvkIyMnF00jr2HwmeCsk_live_51KfjEeLMpUX2gb0IAWHggLH4RM8Pn5I5pVrj1qIgLDT92ED3mTHUNuytL2yeWVEHPsIz3qM9iuC3k9qj8DTnArV400H9gwOxs3
# pk_test_51KfjEeLMpUX2gb0I4NoWZIESIQ8kjQoXhvnPGyJ8stzmrvxA0rHWDJ4tiZGATKnRfvCpmSXEReVKpp8EGIz90tMe000aZ6iG5E
PUBLISHED_KEY = 'pk_live_51KfjEeLMpUX2gb0IEzKGnFNzDLk74MvlUB6zUJfHAZjTjrXKlJZLsMam64BH8i987Oa8deKivTxvnFRRjVd5ntJZ00W35LhnHm'
STRIPE_SECRET_KEY = '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'
STRIPE_ENDPOINT_SECRET = '5883ff1c96d18cb1d269a271b20111a4ae2f622ddb6ad791ed058d094b0'
# stripe listen --forward-to localhost:8000/payment/webhook/
# https://afternoon-brook-19806.herokuapp.com/

# DJANO ON HEROKU
django_on_heroku.settings(locals())
